import Head from 'next/head'
import React from 'react'
interface LandingPageProps {
    children: JSX.Element[]
}
const LandingPage = ({children}:LandingPageProps) => {

  return (
    <section className='_devgrid_landing flex flex-col items-center gap-10 w-full'>
        <Head>
            <title>DevGrid - Web Solutions</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {children.map(el=>el)}
    </section>
  )
}

export default LandingPage
